### ISSUE TITLE
When you hit the back button, keep focus on movie that was clicked, not scroll to top

### ISSUE THREAD

**Issue by grchappell** [sschipke/black-stories-fe#11]

**Comment by sschipke** [comment]
Could try this: https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus

**Comment by grchappell** [comment]
Looks stressful, lol

Garrett Chappell
@garrettdidthis | garrettchappell.com
605-593-7782
He/Him/His

Sent from Mobile

________________________________

**Comment by sschipke** [comment]
React specific https://www.carlrippon.com/scrolling-a-react-element-into-view/

**Comment by sschipke** [comment]
Possible library: https://www.npmjs.com/package/react-router-hash-link
